# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks

# Global properties
separator_block_width=15
markup=none

[wireless]
command=iwgetid -r
interval=5
label=W: 

[volume]
command=~/.config/i3blocks/scripts/volume.sh
interval=1
signal=10
# label=♪ 

[battery]
command=~/.config/i3blocks/scripts/battery.sh
interval=30
# label=🔋 

[disk]
command=df -h / | awk 'NR==2 {print $4}'
interval=30
# label=🖴

[memory]
command=free -h | awk 'NR==2 {print $7}'
interval=10
# label=🧠 

[time_local]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

[time_other]
command=if [ "$(timedatectl show -p Timezone --value)" = "Europe/Stockholm" ]; then TZ='America/Los_Angeles' date '+%H:%M:%S %Z'; else TZ='Europe/Stockholm' date '+%H:%M:%S %Z'; fi
interval=1
